### PR TITLE
Sustitute {callr} dependency

### PR DESCRIPTION
**Pull request by gaborcsardi**
Cf. https://github.com/MangoTheCat/cyclocomp/pull/21

### CODE REVIEW

**Comment by gaborcsardi** [comment]
@lorenzwalthert I merged this, but it seems to break `cyclocomp_package_dir()`. Can you please take a look?

**Comment by lorenzwalthert** [comment]
ufff... Long time... Hopefully before the weekend.

**Comment by lorenzwalthert** [comment]
Ok, so we can't get rid of the {callr} dependency?

**Comment by gaborcsardi** [comment]
> Ok, so we can't get rid of the {callr} dependency?

Not without seriously crippling `cyclocomp_package_dir()`.

**Pull request merged**
